language: objective-c
matrix:
  include:
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode8.3
cache:
  bundler: true
  cocoapods: true
  directories: []
branches:
  only:
    - master
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - sudo motion update
  - (motion --version)
  - (ruby --version)
script:
  - bundle exec rake clean:all spec
  - bundle exec rake clean:all spec bits=64
# - bundle exec rake clean:all spec platform=osx
# - bundle exec rake clean:all spec device_family='iPhone 4s'
# - bundle exec rake clean:all spec device_family='iPhone 5'
# - bundle exec rake clean:all spec device_family='iPad Air'
  - bundle exec rake clean:all
